source "https://github.com/CocoaPods/Specs.git"

target "CocoaPodsTests-iOS" do
  platform :ios, "8.0"
  pod "Kiwi", path: ".."
end

target "CocoaPodsTests-OSX" do
  platform :osx, "10.10"
  pod "Kiwi", path: ".."
end
